"""removed time column

Revision ID: 21de5e8e940d
Revises: 1ac90a68eb80
Create Date: 2021-06-26 21:32:14.934785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21de5e8e940d'
down_revision = '1ac90a68eb80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('creation_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
