"""new user table sctructure

Revision ID: d170c9111ff4
Revises: dddbd19f8a35
Create Date: 2021-06-29 20:21:47.511635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd170c9111ff4'
down_revision = 'dddbd19f8a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_salt')
        batch_op.alter_column('password',sa.String(100))
        batch_op.alter_column('email',sa.String(100))
        batch_op.alter_column('name',sa.String(50))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_salt', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###
